blank_issues_enabled: false
contact_links:
  - name: Give feedback on training materials
    url: https://github.com/deKCD/Training-Materials/issues/new?template=feedback.yml
    about: Suggest improvements or report unclear sections in the tutorials.